# Generated by Django 4.2.2 on 2023-09-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="contact_no",
            field=models.CharField(max_length=50),
        ),
    ]
